"""delete frequency field

Revision ID: d3a09f0cca88
Revises: bed061d93aba
Create Date: 2025-11-05 12:04:55.315694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a09f0cca88'
down_revision: Union[str, Sequence[str], None] = 'bed061d93aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
